[workspace]
members = ["crates/*"]

[patch.crates-io]
musli = { git = "https://github.com/udoprog/musli", branch = "generic-with" }
musli-storage = { git = "https://github.com/udoprog/musli", branch = "generic-with" }
