[package]
name = "web"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
yew = { version = "0.20.0", features = ["csr"] }
lib = { path = "../lib" }
anyhow = "1.0.70"
log = "0.4.17"
wasm-logger = "0.2.0"
web-sys = { version = "0.3.61", features = ["Selection", "Range"] }
yew-router = "0.17.0"
serde = { version = "1.0.160", features = ["derive"] }
wasm-bindgen = "0.2.84"
