[package]
name = "jpv"
version = "0.0.0"
edition = "2021"

[features]
bundle = ["rust-embed", "mime_guess", "webbrowser"]

[dependencies]
anyhow = "1.0.71"
axum = "0.6.18"
tokio = { version = "1.28.0", features = ["full"] }
lib = { path = "../lib" }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
serde = { version = "1.0.160", features = ["derive"] }
clap = { version = "4.2.7", features = ["derive"] }
tower-http = { version = "0.4.4", features = ["cors"] }

rust-embed = { version = "8.0.0", optional = true }
mime_guess = { version = "2.0.4", optional = true }
webbrowser = { version = "0.8.11", optional = true }
